### ISSUE TITLE
plot was not made

### ISSUE THREAD

**Issue by sagitaninta** [xiaoming-liu/stairway-plot-v2#11]
Hi,

I wanna report that I successfully run stairway plot v2 according to the readme in my HPC cluster, but the plot was not made with the following error message:

```
Exception in thread "main" java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.desktop/java.awt.Font.getFont2D(Font.java:497)
	at java.desktop/java.awt.Font.defaultLineMetrics(Font.java:2362)
	at java.desktop/java.awt.Font.getLineMetrics(Font.java:2469)
	at java.desktop/java.awt.font.TextMeasurer.initAll(TextMeasurer.java:239)
	at java.desktop/java.awt.font.TextMeasurer.<init>(TextMeasurer.java:168)
	at java.desktop/java.awt.font.LineBreakMeasurer.<init>(LineBreakMeasurer.java:311)
	at java.desktop/java.awt.font.LineBreakMeasurer.<init>(LineBreakMeasurer.java:278)
	at de.erichseifert.gral.util.GraphicsUtils.getOutline(SourceFile:110)
	at de.erichseifert.gral.graphics.Label.getOutline(SourceFile:191)
	at de.erichseifert.gral.graphics.Label.getCachedOutline(SourceFile:203)
	at de.erichseifert.gral.graphics.Label.getPreferredSize(SourceFile:155)
	at de.erichseifert.gral.graphics.layout.EdgeLayout.a(SourceFile:242)
	at de.erichseifert.gral.graphics.layout.EdgeLayout.getPreferredSize(SourceFile:187)
	at de.erichseifert.gral.graphics.DrawableContainer.getPreferredSize(SourceFile:261)
	at de.erichseifert.gral.graphics.layout.StackedLayout.getPreferredSize(SourceFile:197)
	at de.erichseifert.gral.graphics.layout.StackedLayout.layout(SourceFile:117)
	at de.erichseifert.gral.graphics.DrawableContainer.layout(SourceFile:224)
	at de.erichseifert.gral.graphics.DrawableContainer.add(SourceFile:119)
	at de.erichseifert.gral.graphics.DrawableContainer.add(SourceFile:104)
	at de.erichseifert.gral.plots.legends.AbstractLegend.add(SourceFile:279)
	at de.erichseifert.gral.plots.AbstractPlot.add(SourceFile:581)
	at de.erichseifert.gral.plots.XYPlot.add(SourceFile:1064)
	at Stairway_output_summary_plot2.main(Stairway_output_summary_plot2.java:418)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
	... 25 more
Caused by: java.lang.NullPointerException
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:367)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:312)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 30 more
```

This is my `java --version`:
```
openjdk 11 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

Are there possible incompatibilities between the versions for the plot making? I can make the plot on my own, of course, but it will be helpful to have a standard/reference from how the software would make it.

Thank you in advance for your kind assistance and time for making this awesome method works!

**Comment by nicolashazzi23** [comment]
Hi, Where you able to find a solution to this problem?

**Comment by sagitaninta** [comment]
Hi, I guess I end up able to get the plot but I do not quite remember how. Something to do with how the software choose the java on my HPC system because I have been using a conda environment I suppose. Sorry for the vagueness.

**Comment by zlc952** [comment]
Hello!
May I ask if you have resolved the issue of Java font error? I also encountered the same issue when using stairwayplot2 to generate the pictures
